# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_remove_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(default='kent', upload_to='pictures/'),
        ),
    ]
