# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
