# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0005_auto_20200203_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[(b'Fashion', b'Fashion'), (b'Music', b'Music'), (b'Nature', b'Nature'), (b'Art', b'Art')], default=b'Fashion', max_length=2),
        ),
    ]
